---
fastqdir: "/home/mgalland/data/01_sequencing_runs/20151007_small_RNAs_20_accessions/"
temp_dir: "scratch/"       # will be removed in the end. Store your intermediate files her
result_dir: "results/"     # will be kept.
samples: ["LA0407","LA0716","LA0735","LA1278","LA1364","LA1401","LA1578","LA1718","LA1777","LA1840","LA1954","LA2133","LA2172","LA2386","LA2695","LA4024","LYC4","Moneymaker","PI127826","PI134418"]

# genomic and other references
refs:
  genome: "refs/S_lycopersicum_chromosomes.3.00.fa"
  mirbase:
    mature: "refs/mature.mirbase.release22.fa"
    hairpin: "refs/hairpin.mirbase.release22.fa"

# blastn
blastn:
  mature:
    qcov_hsp_perc:   "100" # Query Coverage Per HSP
    max_target_seqs: "1"   # max number of sequences to keep
  hairpin:
    max_target_seqs: "1"



# ShortStack
shortstack:
  mismatches: "--mismatches 1"          # allows up to X mismatches for a valid alignment
  naln:       "--bowtie_m 50"           # number of possible alignments
  mmap:       "--mmap u"                # u = unique seeded guide for handling multi-mapped reads. Can be f/u/r/n
  dicermin:   "--dicermin 20"           # minimum size of a Dicer-processed small RNA.
  dicermax:   "--dicermax 24"           # maximum size of a Dicer-processed small RNA.
  foldsize:   "--foldsize 1000"         # size of genomic RNA segments for folding for MIRNA search
  pad:        "--pad 100"               # clusters of sRNAs merged if distance less/equal to pad value
  mincov:     "--mincov 20"             # clusters of small RNAs must have at least this many alignments default: 20

# small RNA lengths filtering
length:
  min_length: "18" # will keep everything longer than
  max_length: "25" # will keep everything shorter than

# trimmomatic parameters
trimmomatic:
  LeadMinTrimQual:        '10'       # Cut bases off the start of a read, if below threshold quality of
  TrailMinTrimQual:       '3'        # Cut bases off the end of a read, if below threshold quality of
  windowSize:             '4'        # Scan the read with a 4-base wide sliding window, cutting when the average quality per base drops below 15 (SLIDINGWINDOW:4:15)
  avgMinQual:             '15'       # Scan the read with a 4-base wide sliding window, cutting when the average quality per base drops below 15 (SLIDINGWINDOW:4:15)
  phred:                  '-phred33' # phred: for illumina >1.8 the quality score are encoded by phred33
