__default__:
    account: mgallan1             # your hpc account
    partition: all                # the partition you use
    mail-user: ntpierce@ucdavis.edu # your email (optional!)
    time: 360 # default time (minutes)
    nodes: 1
    ntasks: 1
    mem: 14GB # default memory