---
temp_dir: "scratch/"       # will be removed in the end. Store your intermediate files her
result_dir: "results/"     # will be kept.

# Samples
# "." (dot) are forbidden in the sample column of the samples.tsv file. It will stop pipeline execution. Replace with "_" (underscore)
samples: "config/samples.tsv"


# adapters related to sequencing
fasta_adapters: "config/adapters.fasta"

# genomic and other references
refs:
  mirbase:
    mature: "refs/mature.mirbase.release22.fa"
    hairpin: "refs/hairpin.mirbase.release22.fa"

# blastn
blastn:
  mature:
    qcov_hsp_perc:   "100" # Query Coverage Per HSP
    max_target_seqs: "1"   # max number of sequences to keep
  hairpin:
    max_target_seqs: "1"



# ShortStack
shortstack:
  mismatches: "--mismatches 1"          # allows up to X mismatches for a valid alignment
  naln:       "--bowtie_m 50"           # number of possible alignments
  mmap:       "--mmap u"                # u = unique seeded guide for handling multi-mapped reads. Can be f/u/r/n
  dicermin:   "--dicermin 20"           # minimum size of a Dicer-processed small RNA.
  dicermax:   "--dicermax 24"           # maximum size of a Dicer-processed small RNA.
  foldsize:   "--foldsize 1000"         # size of genomic RNA segments for folding for MIRNA search
  pad:        "--pad 100"               # clusters of sRNAs merged if distance less/equal to pad value
  mincov:     "--mincov 0.5rpm"         # threshold of X reads per million for cluster detection

# small RNA lengths filtering
length:
  min_length: "18" # will keep everything longer than
  max_length: "25" # will keep everything shorter than

# fastp parameters
fastp:
  qualified_quality_phred: "15"     # Phred score threshold for a base to be qualified. >=Q15 is considered OK and qualified.
  average_quality:         "0"      # if read average quality score <avg_qual, then this read/pair is discarded. Default 0 means no requirement (int [=0]) 
  min_length:              "18"     # reads shorter than length_required will be discarded.
  max_length:              "25"     # reads longer than length_limit will be discarded, default 0 means no limitation.
