name: small
channels:
  - bioconda
  - conda-forge
dependencies:
  - samtools = 1.9
  - bowtie = 1.2.0
  - shortstack = 3.8.5  
  - bowtie = 1.2.0
  - trimmomatic=0.38
  - snakemake-minimal = 5.4.3 
  - biopython = 1.74
  - pandas = 0.25.0
  - bioawk = 1.0
  - blast = 2.9
  - viennarna = 2.4.14